### ISSUE TITLE
invada-studio-plugins-lv2 FTBFS on Debian (and Ubuntu)

### ISSUE THREAD

**Issue by eeickmeyer** [falkTX/invada-studio-plugins-lv2#1]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1075091 for information.

**Comment by falkTX** [comment]
I am fine with fixing this, but I am not really upstream. this is just a repo I created in order to store all patches I had so far.

Fixing that build issue is trivial, but I am not the authority for making new releases afterwards.

**Comment by falkTX** [comment]
also that issue was already fixed in 5ecf1dd705e715c035ae4da4c538003396c3bac8
just grab the patches as you need, feel free to submit more if changes are still needed
